# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'field.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(13)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ch1Button = QtWidgets.QRadioButton(self.centralwidget)
        self.ch1Button.setObjectName("ch1Button")
        self.verticalLayout_4.addWidget(self.ch1Button)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelcommand = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华光隶变_CNKI")
        font.setPointSize(12)
        self.labelcommand.setFont(font)
        self.labelcommand.setObjectName("labelcommand")
        self.verticalLayout_5.addWidget(self.labelcommand)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华光隶变_CNKI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华光隶变_CNKI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华光隶变_CNKI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华光隶变_CNKI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(25)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.textEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_7.addWidget(self.textEdit_2)
        self.textEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_3.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_7.addWidget(self.textEdit_3)
        self.textEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_4.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_7.addWidget(self.textEdit_4)
        self.textEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_5.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_7.addWidget(self.textEdit_5)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.voltsdial = QtWidgets.QDial(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltsdial.sizePolicy().hasHeightForWidth())
        self.voltsdial.setSizePolicy(sizePolicy)
        self.voltsdial.setMaximumSize(QtCore.QSize(16777215, 80))
        self.voltsdial.setMinimum(1)
        self.voltsdial.setMaximum(100)
        self.voltsdial.setWrapping(False)
        self.voltsdial.setNotchesVisible(True)
        self.voltsdial.setObjectName("voltsdial")
        self.verticalLayout.addWidget(self.voltsdial)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.labelmag = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelmag.sizePolicy().hasHeightForWidth())
        self.labelmag.setSizePolicy(sizePolicy)
        self.labelmag.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelmag.setAlignment(QtCore.Qt.AlignCenter)
        self.labelmag.setObjectName("labelmag")
        self.verticalLayout.addWidget(self.labelmag)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timedial = QtWidgets.QDial(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timedial.sizePolicy().hasHeightForWidth())
        self.timedial.setSizePolicy(sizePolicy)
        self.timedial.setMaximumSize(QtCore.QSize(16777215, 80))
        self.timedial.setMinimum(1)
        self.timedial.setMaximum(100)
        self.timedial.setSingleStep(1)
        self.timedial.setWrapping(False)
        self.timedial.setNotchesVisible(True)
        self.timedial.setObjectName("timedial")
        self.verticalLayout_2.addWidget(self.timedial)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.labelelec = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelelec.sizePolicy().hasHeightForWidth())
        self.labelelec.setSizePolicy(sizePolicy)
        self.labelelec.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelelec.setAlignment(QtCore.Qt.AlignCenter)
        self.labelelec.setObjectName("labelelec")
        self.verticalLayout_2.addWidget(self.labelelec)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    color: #2f3640;\n"
"    background-color: #f5f6fa;\n"
"    border-color: #2f3640;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    color: #FFFFFF;\n"
"    background-color: #718093;\n"
"    border-color: #2f3640;\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton::pressed,QPushButton::checked{\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #273c75, stop:1 #487eb0);\n"
"}\n"
"\n"
"/**按钮失能情况下样式**/\n"
"QPushButton::disabled{\n"
"    color: #FFFFFF;\n"
"    background-color: #dcdde1;\n"
"    border-color: #dcdde1;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelPath = QtWidgets.QLabel(self.centralwidget)
        self.labelPath.setObjectName("labelPath")
        self.horizontalLayout_3.addWidget(self.labelPath)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-10, 40, 741, 681))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2D_E_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2D_E_2.setEnabled(True)
        self.label_2D_E_2.setText("")
        self.label_2D_E_2.setObjectName("label_2D_E_2")
        self.verticalLayout_8.addWidget(self.label_2D_E_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem)
        self.label_2D_H_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2D_H_2.setText("")
        self.label_2D_H_2.setObjectName("label_2D_H_2")
        self.verticalLayout_8.addWidget(self.label_2D_H_2)
        self.label_2D_E_3 = QtWidgets.QLabel(self.tab)
        self.label_2D_E_3.setGeometry(QtCore.QRect(0, 160, 730, 480))
        self.label_2D_E_3.setText("")
        self.label_2D_E_3.setObjectName("label_2D_E_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3D_EH = QtWidgets.QLabel(self.tab_2)
        self.label_3D_EH.setGeometry(QtCore.QRect(20, 70, 581, 491))
        self.label_3D_EH.setText("")
        self.label_3D_EH.setObjectName("label_3D_EH")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionInformation = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/accu_weather.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInformation.setIcon(icon)
        self.actionInformation.setObjectName("actionInformation")
        self.actionSet = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/android_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet.setIcon(icon1)
        self.actionSet.setObjectName("actionSet")
        self.actionThemes = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/Themes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionThemes.setIcon(icon2)
        self.actionThemes.setObjectName("actionThemes")
        self.actionForward = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/Step_Forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon3)
        self.actionForward.setObjectName("actionForward")
        self.actionBackward = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/Step_Backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackward.setIcon(icon4)
        self.actionBackward.setObjectName("actionBackward")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon5)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon6)
        self.actionPause.setObjectName("actionPause")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/image/images/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon7)
        self.actionStart.setObjectName("actionStart")
        self.actionOpen_file_N = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/image/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file_N.setIcon(icon8)
        self.actionOpen_file_N.setObjectName("actionOpen_file_N")
        self.actionDisplay_scope_S = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/image/images/cpu_tuner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisplay_scope_S.setIcon(icon9)
        self.actionDisplay_scope_S.setObjectName("actionDisplay_scope_S")
        self.menu_F.addAction(self.actionOpen_file_N)
        self.menu_F.addAction(self.actionDisplay_scope_S)
        self.menu.addAction(self.actionInformation)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionOpen_file_N)
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionBackward)
        self.toolBar.addAction(self.actionForward)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionThemes)
        self.toolBar.addAction(self.actionSet)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ch1Button.setText(_translate("MainWindow", "导电介质"))
        self.labelcommand.setText(_translate("MainWindow", "电场幅度(V/m)"))
        self.label_2.setText(_translate("MainWindow", "角频率(*2π rad/m)"))
        self.label_5.setText(_translate("MainWindow", "衰减常数"))
        self.label_6.setText(_translate("MainWindow", "相位差(*π)"))
        self.label_7.setText(_translate("MainWindow", "复波阻抗模值(*π)"))
        self.label.setText(_translate("MainWindow", "Mag Scale"))
        self.labelmag.setText(_translate("MainWindow", "x1"))
        self.label_3.setText(_translate("MainWindow", "Elec Scale"))
        self.labelelec.setText(_translate("MainWindow", "x0.1"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.labelPath.setText(_translate("MainWindow", "文件路径              "))
        self.comboBox.setCurrentText(_translate("MainWindow", "单独显示"))
        self.comboBox.setItemText(0, _translate("MainWindow", "单独显示"))
        self.comboBox.setItemText(1, _translate("MainWindow", "合并显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "2D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "3D"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionInformation.setText(_translate("MainWindow", "Information"))
        self.actionSet.setText(_translate("MainWindow", "Set"))
        self.actionSet.setToolTip(_translate("MainWindow", "设置"))
        self.actionSet.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionThemes.setText(_translate("MainWindow", "Themes"))
        self.actionThemes.setToolTip(_translate("MainWindow", "主题"))
        self.actionThemes.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionForward.setText(_translate("MainWindow", "Forward"))
        self.actionForward.setToolTip(_translate("MainWindow", "加速"))
        self.actionForward.setShortcut(_translate("MainWindow", "F8"))
        self.actionBackward.setText(_translate("MainWindow", "Backward"))
        self.actionBackward.setToolTip(_translate("MainWindow", "减速"))
        self.actionBackward.setShortcut(_translate("MainWindow", "F7"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "停止"))
        self.actionStop.setShortcut(_translate("MainWindow", "F6"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "暂停"))
        self.actionPause.setShortcut(_translate("MainWindow", "F3"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setToolTip(_translate("MainWindow", "运行"))
        self.actionStart.setShortcut(_translate("MainWindow", "F5"))
        self.actionOpen_file_N.setText(_translate("MainWindow", "Open file (&N)"))
        self.actionDisplay_scope_S.setText(_translate("MainWindow", "Display scope (&S)"))

